---
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

# Do not build on tags (GitHub only)
skip_tags: true

environment:
  matrix:
  - nodejs_version: 7
  - nodejs_version: 6
  - nodejs_version: 5
  - nodejs_version: 4
  - nodejs_version: '0.12'
  - nodejs_version: '0.10'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install mocha-appveyor-reporter
  - echo --reporter mocha-appveyor-reporter >> test/mocha.opts

test_script:
  - node --version
  - npm --version
  - npm run test-mocha
  - npm run test-phantomjs
  - npm run check-style

# Don't actually build
build: off
